name = "Bolt"
uuid = "d94d39b4-3f51-4e5a-bfd8-f3b08e8f2b62"
authors = ["Zack Li"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
HCubature = "19dc6840-f33b-545b-b366-655c7e3ffd49"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
NLsolve = "2774e3e8-f4cf-5e23-947b-6d7e65073b56"
NaturallyUnitful = "872cf16e-200e-11e9-2cdf-8bb39cfbec41"
NumericalIntegration = "e7bfaba1-d571-5449-8927-abc22e82249b"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
PhysicalConstants = "5ad8b20f-a522-5ce9-bfc9-ddf1d5bda6ab"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
ThreadPools = "b189fb0b-2eb5-4ed4-bc0c-d34c51242431"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
UnitfulAstro = "6112ee07-acf9-5e0f-b108-d242c714bf9f"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
OrdinaryDiffEq = "5.49"
PhysicalConstants = "0.2"
ForwardDiff = "0.10"
NumericalIntegration = "0.2"
Interpolations = "0.13"
NaturallyUnitful = "0.3"
Parameters = "0.12"
DataStructures = "0.18"
NLsolve = "4.5"
Unitful = "1.5"
UnitfulAstro = "1.0"
BenchmarkTools = "0.5"
UnPack = "1.0"
SpecialFunctions = "1.2"
OffsetArrays = "1.5"
Zygote = "0.6"
ThreadPools = "1, 1.2"
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
